name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-c
      uses: taiki-e/cache-cargo-install-action@v2
      with:
        tool: cargo-c
    - name: Build
      run: cargo build --verbose
    - name: Build (No default features)
      run: cargo build --verbose --no-default-features
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-c
      uses: taiki-e/cache-cargo-install-action@v2
      with:
        tool: cargo-c
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests (No default features + Tokio)
      run: cargo test --verbose --no-default-features --features runtime-tokio
    - name: Run tests (No default features + Smol)
      run: cargo test --verbose --no-default-features --features runtime-smol
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-c
      uses: taiki-e/cache-cargo-install-action@v2
      with:
        tool: cargo-c
    - name: clippy
      run: cargo clippy --verbose -- -Dwarnings
